title: Maryam Taj
logo: "/images/image.png?raw=true"
description: >
  As a Data Scientist with project and academic experience in data analytics, machine learning, and statistical analysis, I hold a Master's degree in Applied Data Science from the University of Essex. Eager to join an organization where I can contribute to meaningful data-driven projects, I am committed to continual learning and growth in this dynamic field. My academic journey has seen me delve into various projects, enhancing my proficiency in Python, R, SQL, and data visualization tools such as Tableau and Power BI.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0


